import type { Metadata } from "next"
import "./globals.css"
import Header from "@/components/shared/header"

export const metadata: Metadata = {
  title: "Circles",
  description: "Generated by create next app",
}

const loadHeader = () => {
  return <Header />
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body className="font-DMSans antialiased h-full w-full flex flex-col">
        <div className="h-[105px]">{loadHeader()}</div>
        <div className="flex-1 overflow-y-scroll">{children}</div>
      </body>
    </html>
  )
}
