import type { Metadata } from "next"
import "./globals.css"
import Header from "@/components/shared/header"
import { HeaderProvider } from "@/components/shared/headerContext"

export const metadata: Metadata = {
  title: "Circles",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body className="font-DMSans antialiased h-full w-full flex flex-col">
        <HeaderProvider>
          <Header />
          <div className="flex-1 overflow-y-scroll">{children}</div>
        </HeaderProvider>
      </body>
    </html>
  )
}
